version: "3.8"

services:

cuda-jupyter:
image: cuda-jupyter:12.2.2
restart: on-failure
build:
context: .
deploy:
resources:
reservations:
devices:
- driver: nvidia
count: all
capabilities: [gpu]
ports:
- "8888:8888"
volumes:
- ./sessions:/workspace